version: "3"

services:
  elasticsearch-2.8:
    container_name: elasticsearch-2.8
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data-2.8:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - ckan-2.8

  publish-2.8:
    image: govuk/publish:latest
    container_name: publish-2.8
    build:
      context: ./src/2.8/datagovuk_publish/
    env_file:
      - .env-2.8
    links:
      - db-2.8:db
      - elasticsearch-2.8:elasticsearch
      - redis-2.8:redis
      - ckan-postdev-2.8:ckan-postdev
    depends_on: 
      - db-2.8
      - elasticsearch-2.8
      - redis-2.8
    # command: bash -c "./bin/setup-docker.sh"
    command: bash -c "tail -f /dev/null"
    volumes:
      - ./src/2.8/datagovuk_publish:/srv/app/datagovuk_publish
      - ./logs/2.8:/var/log/sidekiq
    networks:
      - ckan-2.8

  find-2.8:
    image: govuk/find:latest
    container_name: find-2.8
    build:
      context: ./src/2.8/datagovuk_find/
    env_file:
      - .env-2.8
    links:
      - elasticsearch-2.8:elasticsearch
    depends_on: 
      - elasticsearch-2.8
    # command: bash -c "./bin/setup-docker.sh"
    command: bash -c "tail -f /dev/null"
    volumes:
      - ./src/2.8/datagovuk_find:/srv/app/datagovuk_find
      - ./logs/2.8:/var/log/find
    networks:
      - ckan-2.8
    ports:
      - "4001:3000"

volumes:
  es_data-2.8:

networks:
    ckan-2.8:
        driver: bridge
